In [ ]:
#List example
my_list = ['Do some writing', 'Stop slacking off', 'Do some more writing']

def print_list(LIST): #Create a function for printing list indices and items
    for index, item in enumerate(LIST): #Loop through each index and item
        print(index, item)
        
print_list(my_list) #Print out results

In [ ]:
#Removing an item from a list
my_list.pop(1) #Remove the middle item in the list with the index of 1
my_other_list = my_list.copy() #Copy the contents of my_list to a new list

print_list(my_other_list) #Print out results

In [ ]:
#Adding an item to a list
my_final_list = my_other_list.copy()
new_item = 'Seriously, stop procrastinating!'
my_final_list.append(new_item) #Add new_item onto the end of my_final_list

print_list(my_final_list)

In [ ]:
#Tuple example
import pandas as pd
df_names = pd.DataFrame([['Quaid','Douglas'],['Matrix','John'],['Tasker','Harry']], 
                        columns=['Last_Name','First_Name']) #Add name info
df_names

In [ ]:
#Make tuples from First and Last names
for idx in df_names.index.tolist():
    print(tuple(df_names.iloc[idx,:]))

In [ ]:
#Create Unique ID from first and last names
df_tuple = pd.DataFrame(None) #Blank pandas DataFrame to hold information
for idx in df_names.index.tolist():
    #Next line adds tuples in string form to each DataFrame cell
    df_tuple = pd.concat([df_tuple,pd.Series(str(tuple(df_names.iloc[idx,:])))],axis=0)
df_tuple.reset_index(inplace=True, drop=True) #Reset the index sequence to match df_names
df_tuple.columns=['UID'] #Add column name
df_tuple

In [ ]:
#Mixed data types in lists and tuples
krazy_list = ['Pigs in a blanket', 3, None, False, 3.2]
insane_tuple = ('Pigs in a blanket', 3, None, False, 3.2)

#Function loops through each item in each list/tuple
def list_item_equality(list_one, list_two):
    assert len(list_one) == len(list_two) #Ensures both lists/tuples are the same length
    equality = True #Default value
    for idx in range(len(list_one)):
        if list_one[idx] == list_two[idx]: #If condition is True, passes to next index
            pass
        else:
            equality = False #If condition is False, sets default value to False
    return equality #Outputs default value

print('List equal to tuple?',krazy_list == insane_tuple)
print('List and tuple items equal?',list_item_equality(krazy_list, insane_tuple))

In [9]:
#One-, two-, and three-dimensional arrays
import numpy as np

oneDim = np.array([1,2,3,4], int)
twoDim = np.array([oneDim, oneDim], int)
threeDim = np.array([twoDim, twoDim], int)

print('1D:\n', oneDim, '\n')
print('2D:\n', twoDim, '\n')
print('3D:\n', threeDim, '\n')

1D:
 [1 2 3 4] 

2D:
 [[1 2 3 4]
 [1 2 3 4]] 

3D:
 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]] 



In [23]:
#3D array filled with zeros
zeros = np.zeros((2,2),int)
zeros

array([[0, 0],
       [0, 0]])

In [24]:
z_mtrx = np.matrix(zeros)
z_mtrx

matrix([[0, 0],
        [0, 0]])